{
  imports = [
    ./agtx.nix
    ./aoe.nix
    ./bun.nix
    ./claude-code.nix
    ./colibri.nix
    ./gh.nix
    ./git.nix
    ./herdr.nix
    ./hermes-agent.nix
    ./lazygit.nix
    ./omp.nix
    ./openclaw.nix
    ./opencode.nix
    ./openspec.nix
    ./pi.nix
    ./prime-agent.nix
    ./qmd.nix
  ];
}
