# Reads the pre-decrypted personal secrets JSON (generated by `make decrypt`)
# Uses an absolute path constructed from $HOME to bypass the Nix store copy limitation
# Requires --impure evaluation (already the case in this project via `nh home switch --impure`)
#
# In pure evaluation (CI / `nix flake check`), $HOME is "" and the file won't exist.
# We fall back to placeholder values so the configuration can still be evaluated structurally.
let
  home = builtins.getEnv "HOME";
  decFile = "${home}/.nix/secrets/personal.dec.json";
  placeholder = {
    username = "ci-placeholder";
    primaryEmail = "ci@placeholder.invalid";
    secondaryEmail = "ci@placeholder.invalid";
    workEmail = "ci@placeholder.invalid";
    gpg = {
      keyId = "0000000000000000";
      fingerprint = "0000000000000000000000000000000000000000";
    };
    telegram = {
      userId = "0";
    };
  };
in
if home != "" && builtins.pathExists decFile
then builtins.fromJSON (builtins.readFile decFile)
else placeholder
