# Reads the pre-decrypted personal secrets JSON (generated by `make decrypt`)
# Uses an absolute path constructed from $HOME to bypass the Nix store copy limitation
# Requires --impure evaluation (already the case in this project via `nh home switch --impure`)
let
  decFile = "${builtins.getEnv "HOME"}/.nix/secrets/personal.dec.json";
in
if builtins.pathExists decFile
then builtins.fromJSON (builtins.readFile decFile)
else builtins.throw "Personal secrets not decrypted. Run 'make decrypt' first."
