# Reads the pre-decrypted personal secrets JSON (generated by `make decrypt`)
# Requires --impure evaluation (already the case in this project via `nh home switch --impure`)
let
  file = ./personal.dec.json;
in
if builtins.pathExists file
then builtins.fromJSON (builtins.readFile file)
else builtins.throw "Personal secrets not decrypted. Run 'make decrypt' first."
